### ISSUE TITLE
Gem is duplicative

### ISSUE THREAD

**Issue by jbender** [upmysport/onesignal#32]
This gem appears to do the same things as https://github.com/coding-chimp/onesignal, which is already published to RubyGems as `onesignal`.

**Comment by pvcarrera** [comment]
👍 @aovertus was asking for a published gem in #29

**Comment by jbender** [comment]
@pvcarrera any thoughts on merging efforts across them? All seem to be looking to accomplish the same thing

**Comment by pvcarrera** [comment]
@jbender I’m not against merging projects but in this gem I’m following a different design approach and I would like to continue with it. I’m using this project to experiment and test some of my design ideas and I wouldn't want to give them up.
